parameters:
    hexmedia.assetic.filter.assetsurl.class: Hexmedia\AsseticBundle\Filter\AssetsUrl

services:
    hexmedia.assetic.filter.assetsurl:
        class: %hexmedia.assetic.filter.assetsurl.class%
        arguments:
            - "@service_container"
        tags:
            -	{ name: assetic.filter, alias: assetsurl }