language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

env:
  - SYMFONY_VERSION=2.3.* DEV=
  - SYMFONY_VERSION=2.4.* DEV=
  - SYMFONY_VERSION=2.5.* DEV=
  - SYMFONY_VERSION=2.6.*@dev DEV=--dev

matrix:
    allow_failures:
        - php: hhvm-nightly

before_script:
    - echo "composer require symfony/symfony:${SYMFONY_VERSION} ${DEV}"
    - composer require symfony/symfony:${SYMFONY_VERSION} ${DEV}
    - composer install
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "5.3.3" ]; then phpunit --self-update; fi;'
