language: php

php:
    - 5.3
    - 5.3.3
    - 5.3.4
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly


matrix:
    allow_failures:
        - php: hhvm-nightly
        - php: 5.3.3

before_script:
    - COMPOSER_ROOT_VERSION=dev-master composer --no-dev install
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "5.3.3" ]; then phpunit --self-update; fi;'
